#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "hardware/gpio.h"
#include <math.h>
#include <string.h>
#include "pico/stdlib.h"
#include "pico/float.h"     // Required for using single-precision variables.
#include "pico/double.h"    // Required for using double-precision variables.
// Must declare the main assembly entry point before use.
#include "ws2812.pio.h"     // the autogenerated header file

#define IS_RGBW true
#define NUM_PIXELS 150

#define WS2812_PIN 28

static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}

static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return
            ((uint32_t) (r) << 8) |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}

void main_asm();

int arrayIndex();
int input_array();

// Wait for button interrupt entry point
extern void wait_for_input();

// Initialise a GPIO pin – see SDK for detail on gpio_init()
void asm_gpio_init(uint pin) {
    gpio_init(pin);
}

// Enable falling-edge interrupt – see SDK for detail on gpio_set_irq_enabled()
void asm_gpio_set_irq(uint pin) {
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_FALL, true);
}

// Enable Rising-edge interrupt – see SDK for detail on gpio_set_irq_enabled()
void asm_gpio_set_irq_rise(uint pin) {
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_RISE, true);
}
void watchdog_update_arm(){
    watchdog_update();
}
void displayStatistics(int totalCorrect, int totalIncorrect){
    printf("Statistics of this level:\n");
    printf("Total correct answers: %d\n", totalCorrect);
    printf("Total incorrect answers: %d\n", totalIncorrect);
    int total = totalCorrect + totalIncorrect;
    float res = totalCorrect/total;
    res *= 100;
    printf("Overall accuracy: %.2f%% \n\n", res);
}
    
/*
 * Main entry point for the code - simply calls the main assembly function.
 */
absolute_time_t time1, time2;
uint64_t diff;
int totalCorrect = 0, totalIncorrect = 0, streak  = 0, level = 0, levelScreen = 0, lives = 3, r;
bool running = true;
int main() {
    main_asm();                    // Initialize alarms and button
    stdio_init_all();              // Initialise all basic IO
    PIO pio = pio0;
    int sm = 0;
    uint offset = pio_add_program(pio, &ws2812_program);

    ws2812_program_init(pio, sm, offset, WS2812_PIN, 800000, IS_RGBW);
    
    uint32_t blueColor = urgb_u32(0,0,0x4F);
    uint32_t greenColor = urgb_u32(0,0x4F,0);
    uint32_t yellowColor = urgb_u32(0x4F,0x4F,0);
    uint32_t orangeColor = urgb_u32(0x4F,0x13,0);
    uint32_t redColor = urgb_u32(0x4F,0,0);
        
    if (watchdog_caused_reboot()){
        printf("\nNo input was detected for 8 seconds!\n Current game has been stopped, returning to homepage\n\n");
    }
    put_pixel(blueColor); // pre-game color
    time1 = get_absolute_time(); // Time 1
    //srand(time(0));
    printf("Group:\n");
    printf("32\n");
    printf("----------------------------------------\n|                                       |\n|           MORSE CODE GAME             |\n|                                       |\n----------------------------------------\nSELECT LEVEL USING GP21\nLevel 1: -----  EASY\nLevel 2: .----  HARD\n");
    int * test =  input_array;
    char* morse[36][2]= {{"A", ".-"}, {"B", "-..."},{"C", "-.-."},{"D", "-.."},{"E", "."},{"F", "..-."},{"G", "--."},
	{"H", "...."},{"I", ".."}, {"J", ".---"}, {"K", "-.-"}, {"L", ".-.."}, {"M", "--"}, {"N", "-."}, {"O", "---"},
	{"P", ".--."}, {"Q", "--.-"}, {"R", ".-."}, {"S", "..."}, {"T", "-"}, {"U", "..-"}, {"V", "...-"}, {"W", ".--"},
	{"X", "-..-"}, {"Y", "-.--"}, {"Z", "--.."}, {"0", "-----"}, {"1", ".----"}, {"2", "..---"}, {"3", "...--"},
	{"4", "....-"}, {"5", "....."}, {"6", "-...."}, {"7", "--..."}, {"8", "---.."}, {"9", "----."}};

    while(running == true){ // wait for morse code to be input by user
        if(levelScreen == 0){
        wait_for_input();
        time2 = get_absolute_time();
        uint64_t diff = absolute_time_diff_us (time1, time2);
        int rseed = (int) diff;
        srand(rseed);
        int* nextInput;
        nextInput = test;
        char nextChar[5] = "";
        while (*nextInput != -1){
            char number = *nextInput + ',';
            strncat(nextChar, &number, 1);
            nextInput += 1;
        }
        printf("Sequence inputted: \n %s\n", nextChar);
        bool found = false;
        if (strcmp(nextChar, "-----") == 0){
                level = 1;
                levelScreen++;
                printf( "Level 1 Chosen!\n\n");
                watchdog_enable(0x7fffff, 1); //enabling timer where 0x7fffff, which is approximately 8.3 seconds is the maximum timer count watchdog can contain
        }
        else if (strcmp(nextChar, ".----") == 0){
                level = 2;
                levelScreen++;
                printf( "Level 2 Chosen!\n\n");
                watchdog_enable(0x7fffff, 1); //enabling timer where 0x7fffff, which is approximately 8.3 seconds is the maximum timer count watchdog can contain
        }
        else printf(" ?\n");
        }
        else{
        if(lives == 3) put_pixel(greenColor);
        else if(lives == 2) put_pixel(yellowColor);
        else if(lives == 1) put_pixel(orangeColor);
        r = rand() % 36;
        if(level == 2) printf("Please input the character %s in morse code\n", morse[r][0]);
        else printf("Please input the character %s in morse code\n %s\n", morse[r][0], morse[r][1]);
        wait_for_input();

        int* nextInput;
        nextInput = test;
        char nextChar[5] = "";
        while (*nextInput != -1){
            char number = *nextInput + '0' -4;
            strncat(nextChar, &number, 1);
            nextInput += 1;
        }
        printf("Sequence inputted: \n %s \n", nextChar);
        bool found = false;
        for (int i = 0; i < 36; i++){
            if (strcmp(nextChar, morse[i][1]) == 0){
                found = true;
                printf("Sequence decoded to character: %s \n\n", morse[i][0]);
                if (i == r){
                    if(lives < 3){
                        lives++;
                    }
                    printf( "CORRECT!\n\n");
                    totalCorrect++;
                    streak++;
                }
                else{
                    if(lives == 1){
                        put_pixel(redColor);
                        running = false;
                    }
                    printf("INCORRECT!\n\n");
                    streak = 0;
                    lives--;
                    totalIncorrect++;
                }
                break;
            }
        }
          if(found == false){
          printf( " ?\n");
          if(lives == 1){
            put_pixel(redColor);
            running = false;
          }
          lives--;
          totalIncorrect++;
          streak = 0;
        }
        if(lives == 0){
             printf("GAME LOST!\n");
        }
        else printf("Currently on a streak of %d correct answers for this level!\n", streak);
        if(streak == 5){
            if(level == 2){
                 printf("Congratulations, you have WON the game!\n");
                 running = false;
            }
            if(level == 1){
                level = 2;
                printf("Congratulations, you have moved to LEVEL 2!\n\n");
                displayStatistics(totalCorrect, totalIncorrect);
                streak = 0;
            } 
        }
        if(running == false) displayStatistics(totalCorrect, totalIncorrect);
        }
    }
    return 0;
}
